// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const SOTRAGE_PRISMA_DATABASE_URL = process.env.SOTRAGE_PRISMA_DATABASE_URL;

if (!SOTRAGE_PRISMA_DATABASE_URL) {
  throw new Error("SOTRAGE_PRISMA_DATABASE_URL is missing");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: SOTRAGE_PRISMA_DATABASE_URL,
  },
});
